### ISSUE TITLE
[🐛] Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri

### ISSUE THREAD

**Issue by maestrolsj** [react-native-image-picker/react-native-image-picker#1567]
### Description

[ Android ]
it failed to read content after fetching uri from **google photo**

`  Unhandled promise rejection [Error: Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/1/content:/media/external/images/media/1259/ORIGINAL/NONE/image/jpeg/1615980699 from pid=20074, uid=10303 requires the provider be exported, or grantUriPermission()]`

### How to repeat issue and example

- step to reproduce the issue
- open google photo  and choose file
- and read file as base64
`   const base64Content = await RNFetchBlob.fs.readFile(
      decodeURIComponent(filePath),
      "base64"
    );`

### Solution

Need to inform how to handle ungranted permission

### Additional Information

- Image Picker version: [ "react-native-image-picker": "3.0.0-vnext.4".]
- React Native version: [ "react-native": "^0.63.2".]
- Platform: [Android]
  buildToolsVersion = "29.0.2"
  minSdkVersion = 24
  compileSdkVersion = 29
  targetSdkVersion = 29
  supportLibVersion = "28.0.0"
- Development Operating System: [MacOs]
- Dev tools: [vscode]

**Comment by ravirajn22** [comment]
Update to latest version and check if this issue happens

**Comment by maestrolsj** [comment]
> Update to latest version and check if this issue happens
Thank you
it works with
 react-native-image-picker@^3.1.3

**Comment by stefanoeb** [comment]
Having the same issue, but when trying to read from `response.uri`.
Same error on `react-native-image-picker@^3.1.3`

**Comment by efstathiosntonas** [comment]
this came into crashlytics today:

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/963/ORIGINAL/NONE/image/jpeg/1882044403 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F963/ORIGINAL/NONE/image%2Fjpeg/1882044403} }} to activity {com.XXX/com.XXXX.MainActivity}: java.lang.NullPointerException: uri
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4544)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4586)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:205)
       at android.app.ActivityThread.main(ActivityThread.java:6991)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

i'm using `3.2.1`

**Comment by ravirajn22** [comment]
@efstathiosntonas thanks for the stack trace, the error is happening on Android ContentResolver.query. So I feel its a rare issue on android side. Keep an eye on the crash reports and ping me if there is lot of reports.

**Comment by efstathiosntonas** [comment]
@ravirajn22 sure, it appeared only one time, will keep track.

**Comment by minhchienwikipedia** [comment]
Any update? I'm still getting this issue!

**Comment by stefanoeb** [comment]
It seems to be an issue when reading from photos saved in Google Photos.
I've worked around this problem with a solution that looks like this:
```ts

import RNFetchBlob from 'rn-fetch-blob';
// ...
export async function getPathForFirebaseStorage(uri: string) {
  // The reason we have this function is that on android if the file comes from google photos we can't access it directly
  if (Platform.OS === 'ios') {
    return uri;
  }

  if (!uri.includes('content://com.google')) {
    return uri;
  }

  const stat = await RNFetchBlob.fs.stat(uri);
  return stat.path;
}

```

The function above will receive the path given by the picker and then return a proper path you can read from without any permission error

**Comment by ravirajn22** [comment]
Latest version returns fileUri for images.
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

**Comment by luklew** [comment]
I am getting similar error, when trying to pick video files: 
``` Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider```
```    "react-native-image-picker": "^4.7.1",```

**Comment by rdjuric** [comment]
@ravirajn22 

It's still returning the content:// path for videos

`Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/2/mediakey:/local%3Af32464a1-46cf-40a5-9a22-99da30478e92/ORIGINAL/NONE/video/mpeg/982110991 from pid=7300, uid=10154 requires the provider be exported, or grantUriPermission()`

**Comment by KMint1819** [comment]
For people that didn't solve the problem using the [above solution](https://github.com/react-native-image-picker/react-native-image-picker/issues/1567#issuecomment-798494218), double check if the image was actually in the local device or in Google Photos Cloud...
