### ISSUE TITLE
[🐛] Returns invalid mime types (`image/jpg`) instead of the correct `image/jpeg`

### ISSUE THREAD

**Issue by dylanpyle** [react-native-image-picker/react-native-image-picker#1856]
### Description

When you select a photo from the library or camera, `response.assets` includes an array of assets and metadata e.g:

```
[
    {
        "type": "image/jpg",
        "fileName": "8F471139-AB15-457B-A817-EF41BF621231.jpg",
        "width": 3024,
        "height": 4032,
        "uri": "file:///var/mobile/Containers/Data/Application/CA9B8D34-12F7-41A6-9364-FEBF5C536BAD/tmp/8F471139-AB15-457B-A817-EF41BF621231.jpg",
        "fileSize": 6718368
    }
]
```

Though the readme doesn't use the phrase "mime type" or promise to adhere to any specific standard, the format of the `type` field suggests it's supposed to be a "mime type", which is a specific [set of standards defined by IANA/IETF](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)

`image/jpg` isn't a valid mime type (`image/jpeg` is the correct type to use), and most databases (e.g. [mime-db](https://github.com/jshttp/mime-db/blob/master/db.json#L7039)) can't decode `image/jpg` into something useful.

This may the case for other types (I haven't checked) but is definitely wrong for JPGs.

### How to repeat issue and example

Select an image and inspect the `response.assets` array.

### Solution

Return the valid `"type": "image/jpeg"` for JPG files.

### Additional Information

- Image Picker version: 4.1.1
- React Native version: 0.63.3
- Platform: iOS
- Development Operating System: macOS
- Dev tools: Xcode 12.5.1

**Comment by yberstad** [comment]
I fixed this issue by creating a patch-file, `react-native-image-picker+4.3.0.patch:`
```
diff --git a/node_modules/react-native-image-picker/ios/ImagePickerUtils.m b/node_modules/react-native-image-picker/ios/ImagePickerUtils.m
index a611b74..3ae322a 100644
--- a/node_modules/react-native-image-picker/ios/ImagePickerUtils.m
+++ b/node_modules/react-native-image-picker/ios/ImagePickerUtils.m
@@ -93,13 +93,13 @@ + (NSString*) getFileType:(NSData *)imageData
     [imageData getBytes:&firstByte length:1];
     switch (firstByte) {
       case firstByteJpg:
-        return @"jpg";
+        return @"jpeg";
       case firstBytePng:
         return @"png";
       case firstByteGif:
         return @"gif";
       default:
-        return @"jpg";
+        return @"jpeg";
     }
 }
```

**Comment by AleksandrTermenzhy** [comment]
It seems like there is one more change required. Pls, correct me if I'm wrong:

```
diff --git a/node_modules/react-native-image-picker/ios/ImagePickerManager.m b/node_modules/react-native-image-picker/ios/ImagePickerManager.m
index 112660a..7a26302 100644
--- a/node_modules/react-native-image-picker/ios/ImagePickerManager.m
+++ b/node_modules/react-native-image-picker/ios/ImagePickerManager.m
@@ -126,7 +126,7 @@ -(NSMutableDictionary *)mapImageToAsset:(UIImage *)image data:(NSData *)data phA
                                     maxHeight:[self.options[@"maxHeight"] floatValue]];
     }
 
-    if ([fileType isEqualToString:@"jpg"]) {
+    if ([fileType isEqualToString:@"jpeg"]) {
         data = UIImageJPEGRepresentation(image, [self.options[@"quality"] floatValue]);
     } else if ([fileType isEqualToString:@"png"]) {
         data = UIImagePNGRepresentation(image);
```

**Comment by Aure77** [comment]
Any PR with this fix ?

**Comment by AdnanAshraf-gol** [comment]
Any update on this ?still facing this issue ..
IPhone camera pics are heif and its give jpg .

**Comment by dmmiller** [comment]
+1 on still hitting this.  Any update on a fix?

I am on 8.2.1
