### ISSUE TITLE
[🐛] The image library picker freezes on iOS 18

### ISSUE THREAD

**Issue by changey** [react-native-image-picker/react-native-image-picker#2312]
### Description

on iOS 18 beta, the image library picker freezes upon opening as shown in the below video clip. It should probably be fixed.

https://github.com/react-native-image-picker/react-native-image-picker/assets/1524485/9c6399c1-d609-4e6e-b5da-bf52330ce0d0

### How to repeat issue and example

What's required for testing:

- iOS 18.0 beta 1
- Xcode Version 16.0 beta 1 (or Xcode 15 that runs an iOS 18 beta simulator)

- step to reproduce the issue

1. Install and open the example app
2. Press the "Select Image" option
3. Select an image or click on the "Cancel" on the upper left corner

Expected result:
- The image library picker should be responsive

Actual result:
- The image library picker freezes

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: 7.1.2
- React Native version: 0.73.6
- Platform: iOS
- Development Operating System: MacOS
- Dev tools: Xcode Version 16.0 beta 1 (or Xcode 15 that runs an iOS 18 beta simulator), iOS 18.0 beta 1

**Comment by sayurimizuguchi** [comment]
Do you have any news about this issue? I was able to reproduce it on my end.

RN v74.2
Image Picker version: 7.1.2
React Native version: 0.73.6
Platform: iOS
Development Operating System: MacOS
Dev tools: Xcode Version 16.0 beta - Simulator iOS 18.0 beta 1

**Comment by deepakOptimizeApp** [comment]
I am also facing same issue

**Comment by HumayounBaig** [comment]
Hi there facing the same issue after updating to 
ios 18.

Any update on it?

**Comment by davoam** [comment]
We have the same issue in the simulator, but on a real device with iOS 18 the picker works

**Comment by creativecreatorormaybenot** [comment]
Happens on iOS 18 **simulators** (not just the beta but the new full release).

**Comment by ansarikhurshid786** [comment]
I am facing issue

**Comment by emrecan-er** [comment]
same here.

**Comment by Johan-dutoit** [comment]
I've updated the example app, previously it too was freezing but now it no longer freezes.
Hope that helps in debugging the issue.

**Comment by sohums** [comment]
Hmm I am still seeing this freeze on my simulator even on iOS 18.1. Anyone have a solution that works for them?

**Comment by iadwait** [comment]
This issue seems to be Apple issue, I am doing iOS Development and Facing Same issue on iOS 18.2 simulator while it works fine on iOS 17.x simulators.
Hoping it should work at least on real device.

**Comment by MMYurt** [comment]
It looks like a generic Apple issue as others mentioned. https://forums.developer.apple.com/forums/thread/765079 
You can give it a try with including arm64 architecture (I don't know it is possible now, it wasn't in older versions of RN.)

**Comment by AmitDigga** [comment]
Fixed


Steps:
1. Commented `EXCLUDED_ARCHS` from `Podfile`
```
target.build_configurations.each do |config|
      # config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
end
```

2. Removed lines in `ios/MyApp.xcodeproj/project.pbxproj` which excluded arm64.

**Comment by ahmedsabahi** [comment]
The issue appears to occur when arm64 is excluded for the simulator.
To resolve it, go to Runner > Build Settings > Excluded Architectures and remove arm64.

**Comment by imki123** [comment]
I'm facing a same issue in iOS 18.x simulator
It works well on iOS 17.x

**Comment by rckm** [comment]
Issue is still exist on iOS 18.x versions simulator
It works well on iOS 26 real device (and maybe any iOS version real device)

**Comment by ipektrc** [comment]
Still experiencing launchImageLibrary freeze on iOS 18.6.2

Description
I'm still experiencing the same freezing issue with launchImageLibrary on iOS 18.6.2, both on real devices and simulators. The image picker opens but becomes completely unresponsive - can't select images, can't cancel, and the interface freezes.

Environment Details
Image Picker version: 8.2.1
React Native version: 0.81.4
React Native CLI version: 20.0.0
Platform: iOS 18.6.2 (both simulator and real device)
Development OS: macOS 15.0.1
Xcode version: 16.1 (Build version 16B40)
Development tools: Xcode 16.1, iOS 18.6.2

Steps to Reproduce
Install and run the app on iOS 18.6.2 device/simulator
Trigger launchImageLibrary function
Image picker modal opens
Interface becomes completely frozen - cannot select images or cancel

Expected Behavior
Image picker should be responsive
Should be able to select images or cancel the picker

Actual Behavior
Image picker opens but freezes immediately
No interaction possible (cannot select images, cannot cancel)
App becomes unresponsive until force-closed

**Comment by emirariemir** [comment]
Issue is still persisting for 18.x iOS simulators

**Comment by alainib** [comment]
i get freeze to on simulator with ios 18.6

**Comment by valentinlm-uggy** [comment]
Same issue on iOS 18 simulator

**Comment by JorgeWSantos** [comment]
Same issue on the iOS 18.1 simulator in 2026. I changed to iOS 17.5, and it worked.

**Comment by adeelcheeema** [comment]
@ipektrc  @JorgeWSantos Same issue on iOS 18.6.2 — happening on both real devices and the simulator. Has anyone fixed this or switched to another library that resolves it?

**Comment by FabiodzDev** [comment]
I managed to resolve this by updating to the latest version of Xcode along with the iOS 26.2 simulator.
